# Site settings
title: Rivalry!
email: rivalryapp@gmail.com
description: >
  Rivalry! lets you show your true colors and represent your affiliation. Whether proving to your friends you're a bigger fan or rising up to the challenge of your rivals, Rivalry! makes it known where you stand.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://rivalryapp.com" # the base hostname & protocol for your site
twitter_username: rivalryapp
github_username:  rivalry-tech

# Navigation
navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Rules
   url: /rules

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
